# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[battery]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [kubernetes]
# # format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
# format = 'on [⛵ $context \($namespace\)](dimmed green) '
# # format = 'on [⎈ ($cluster) ](#FFA500)'
# # style = "dimmed green"
# disabled = false
# contexts = [
#   { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
# ]

# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"
