# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[battery]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [kubernetes]
# # format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
# format = 'on [⛵ $context \($namespace\)](dimmed green) '
# # format = 'on [⎈ ($cluster) ](#FFA500)'
# # style = "dimmed green"
# disabled = false
# contexts = [
#   { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
# ]

# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"
