#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
  alias $command="sudo $command"
done
unset command

se() {
  choice="$(find ~/.local/bin/ -mindepth 1 -printf '%P\n' | fzf)"
  [ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -Priv" \ # no symlink, recursive
  mv="mv -iv" \
  ln='ln -i' \
  mkd="mkdir -pv" \
  ffmpeg="ffmpeg -hide_banner" \
  ffprobe='ffprobe -hide_banner'
  rm="rm -vI --preserve-root"
  #Do not accidentally delete root, and also,
  #prompt if deleting more than 3 files at a time
  #(this has saved my ass more times than you would think)
alias \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto" \
  llll="du -sh *" \
  dus="du -h --max-depth=1 | sort -rh" \
  ls="eza -a --icons" \
  la="eza -A" \
  ll="eza -lAh --icons --tree --level=1" \
  lll="stat -c '%A %a %n' *" \
  l="ls -Fh" \
  lm='ls -m' \
  lr='ls -R' \
  l.='ls -AF -d .*' \
  ll='ls -lah --color=auto' \
  lcd="cd" \
  home="cd ~" \
  du='du -ch' \
  rgg='rg --files --glob' \
  cat='bat'

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  trem="transmission-remote" \
  sdn="shutdown -h now" \
  e='$EDITOR' \
  z="zathura-sandbox" \
  v="nvim" \
  vi="nvim" \
  lg="lazygit" \
  kx="kubectx" \
  k="kubectl"

alias \
  ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc' \
  weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

alias \
  i2pstart="sudo systemctl start i2prouter.service" \
  i2pstart="sudo systemctl stop i2prouter.service" \
  dirsize="du -sh" \
  lsblk="lsblk -f -o +SIZE,MODEL" \
  myip="dig +short myip.opendns.com @resolver1.opendns.com" \
  myip2="curl https://ipinfo.io/ip" \
  myip3="curl -s ifconfig.me" \
  myip4='curl ipinfo.io/ip'   \
  rand="head -c 50K < /dev/urandom > $1" \
  s="sudo -s" \
  c="clear" \
  cls="clear" \
  clr="tput reset" \
  q="exit" \
  :q="exit" \
  quit="exit" \
  dusort='du -hs * . | sort -h' \
  df="df --exclude-type=tmpfs --exclude-type=devtmpfs -h" \
  free="free -mht" \
  da='date "+%Y-%m-%d %A %T %Z"' \
  now2="echo -e $(date +'%H:%M')" \
  mute="pamixer -m" \
  unmute="pamixer -u" \
  netprocs="lsof -P -i -n" \
  dd='dd status=progress' \
  sha1='openssl sha1'

# Toggle touchpad
alias touchoff="xinput set-int-prop 14 'Device Enabled' 8 0"
alias touchon="xinput set-int-prop 13 'Device Enabled' 8 1"
alias touchon2="xinput set-int-prop 14 'Device Enabled' 8 1"

alias zathura='zathura-sandbox'
alias grep='grep --color=auto -iE'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias ipa='ip a|grep -w inet'
alias s='sudo -i'
alias s-d='systemctl daemon-reload'
alias s-l='systemctl list-units --no-pager'
alias s-re='systemctl restart'
alias s-s='systemctl status'
alias s-sp='systemctl stop'
alias s-st='systemctl start'

alias passgen="pwgen -Ccsn 32 1"
alias nsl="nslookup"

alias top='top -c -n 1'

alias pkg_size="expac -H M '%m\t%n' | sort -h"

alias heic_to_png="magick mogrify -monitor -format png *.HEIC"
alias lazydocker="upscope lazydocker"
alias path="echo $PATH | tr -s ':' '\n'"
alias genpass="openssl rand -base64 20"

[[ $TERM == "xterm-kitty" ]] && alias ssh="kitty +kitten ssh"

#alias config='git --git-dir=$HOME/dotfiles/ --work-tree=$PWD'
#alias for dotfiles bare repo
#alias dots='/usr/bin/git --git-dir=$HOME/.local/src/dotfiles/ --work-tree=$HOME'
alias dots='lg -w $HOME -g $HOME/.local/src/dotfiles/'
alias ddiff='/usr/bin/git --git-dir=$HOME/.local/src/dotfiles/ --work-tree=$HOME diff'
alias ds='/usr/bin/git --git-dir=$HOME/.local/src/dotfiles/ --work-tree=$HOME status -uno'
alias da='/usr/bin/git --git-dir=$HOME/.local/src/dotfiles/ --work-tree=$HOME add'
alias last='git log --oneline --graph --decorate --all'
alias by="systemctl poweroff -i"

alias hgrep="history|grep"
alias fuck='sudo $(history -p !!)'
#alias fuck="sudo !!"
alias pls='sudo $(fc -ln -1)'

alias za="zathura --fork"
alias l.='eza -d .* --color=auto'
alias ports='sudo netstat -tulanp'
alias f="find . | grep "

alias incognito='unset HISTFILE'
alias temps='watch -n .1 sensors'
alias getip="curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"
alias weather='curl wttr.in/cmb?0'
alias weatherfull='curl wttr.in/cmb'
#alias weather='curl "wttr.in/<your city>?A,F,Q,2"''
#alias up='uptime -p'
alias mpvl='mpv --loop '
alias enlarge_tmp='sudo mount -o remount,size=16G /tmp/'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

alias more="less -Ri"

# youtube-dl
alias yta-aac='yt-dlp -c --extract-audio --audio-format aac --output "%(title)s.%(ext)s"'
alias yta-best='yt-dlp -c --extract-audio --audio-format best --output "%(title)s.%(ext)s"'
alias yta-flac='yt-dlp -c --extract-audio --audio-format flac --output "%(title)s.%(ext)s"'
alias yta-m4a='yt-dlp -c --extract-audio --audio-format m4a --output "%(title)s.%(ext)s"'
alias yta-mp3='yt-dlp -c --extract-audio --audio-format mp3 --output "%(title)s.%(ext)s"'
alias yta-opus='yt-dlp -c --extract-audio --audio-format opus --output "%(title)s.%(ext)s" '
alias yta-vorbis='yt-dlp -c --extract-audio --audio-format vorbis --output "%(title)s.%(ext)s"'
alias yta-wav='yt-dlp -c --extract-audio --audio-format wav --output "%(title)s.%(ext)s"'
alias ytv-best='yt-dlp -c -f bestvideo+bestaudio --output "%(title)s.%(ext)s" '
alias ytv-360='yt-dlp -c -f 18 --output "%(title)s.%(ext)s"'
alias yta='yt-dlp -c -x -f ba --audio-format opus --output "%(title)s.%(ext)s"'
alias ytt="yt-dlp --no-download --write-thumbnail "
#alias youtube-audio='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0'
#alias ytmp3='youtube-dl --add-metadata -x --audio-format mp3 --output "%(title)s.%(ext)s" --audio-quality 0 --add-metadata --exec "mv {} /home/adri/Music/" $(xclip -o) && notify-send "youtube-dl" "download complete !"'

#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"

# get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"
alias jctl2="journalctl -p 3 -xeb"
alias journal='sudo journalctl -b -p 3'

#verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
#receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

#shutdown or reboot
alias ssn="sudo shutdown now"
alias sr="sudo reboot"
alias sn="shutdown now"
#alias rebootsafe='sudo shutdown -r now'
#alias rebootforce='sudo shutdown -r -n now'

alias userlist="cut -d: -f1 /etc/passwd"

alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

# add new fonts
alias update-fc='sudo fc-cache -fv'

alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'

#get fastest mirrors in your neighborhood
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias mirrorx="sudo reflector --age 6 --latest 20 --fastest 20 --threads 5 --sort rate --protocol https --save /etc/pacman.d/mirrorlist"
alias mirrorxx="sudo reflector --age 6 --latest 20 --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist"

#mounting the folder Public for exchange between host and guest on virtualbox
alias vbm="sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/$USER/Public"

alias openports='netstat -nape --inet'

# reduce 50%
alias picresize='convert pic.png -resize 50%%%% pic_resized.png'

if [[ $(uname) == "Linux" ]] ; then
  alias yi="yay -S"
  alias yn="yay -S --noconfirm" # установка без подтверждения.
  alias ys="yay"                # поиск с дальнейшим выбором по цифре.
  alias ysn="yay --noconfirm"   # поиск с дальнейшим выбором по цифре, без подтверждения.
  alias yc="yay -Sc"            # частичная очистка кэша.
  alias yy="yay -Syy"           # синхронизация баз зеркал.
  alias yu="yay -Syu"           # обновление
  alias yun="yay -Syu --noconfirm"
  alias yr="yay -R"
  alias yrn="yay -R --noconfirm"
  alias yl="yay -Q | grep"
  alias yayskip='yay -S --mflags --skipinteg' # skip integrity check
  alias pacman='sudo pacman --color auto'
  alias up='yay -Syyu --devel'
  alias pksyua="yay -Syu --noconfirm"
  alias all="yay -Syu --noconfirm"
  alias cleanup='sudo pacman -Rns $(pacman -Qtdq)' # cleanup orphaned packages
  alias clean="sudo pacman -Scc"
  alias unlock="sudo rm /var/lib/pacman/db.lck"
  #alias programs='pacman -Qe | grep -v "`pacman -Qqeg base-devel base`"'
  #alias pack="clear && echo && echo -e '\e[1m\e[4m\e[93mINSTALLED PACKAGES SORTED BY SIZE - TOP 25\e[39m\e[0m' && pacman -Qi | awk '/^Name/{name=\$3} /^Installed Size/{print \$4\$5, name}' | sort -hr | head -25 | sed 's/^/ /' | lolcat"
  #alias pac="expac --timefmt='%F %T' '%l %n' | sort -n"
fi

alias wg='wget -O /dev/null'

alias clearjournal="sudo journalctl --flush --rotate --vacuum-time=1s;sudo journalctl --user --flush --rotate --vacuum-time=1s"
alias renew="source ~/.zprofile"

#alias rsync-copy="rsync -avz --progress -h"
#alias rsync-move="rsync -avz --progress -h --remove-source-files"
#alias rsync-update="rsync -avzu --progress -h"
#alias rsync-synchronize="rsync -avzu --delete --progress -h"
#alias rscp="rsync --partial --progress --archive"

#ftext () {
#grep -iIHrn --color=always "$1" . | less -R -r
#}

#duplicatefind ()
#{
#find -not -empty -type f -printf "%s\n" | sort -rn | uniq -d | xargs -I{} -n1 find -type f -size {}c -print0 | xargs -0 md5sum | sort | uniq -w32 --all-repeated=separate
#}

# more simplified duplicatefind
#duplicatefiles ()
#{
#cksum * 2> /dev/null | sort | awk '
#{ checksum = $1; bytecount = $2; $1 = $2 = ""; filename = $0
#if (checksum == prev_checksum && bytecount == prev_bytecount)
#printf("%s\n%s\n\n", prev_filename, filename);
#prev_checksum = checksum
#prev_bytecount = bytecount
#prev_filename = filename
#} '
#}

#generateqr ()
#{
#printf "$@" | curl -F-=\<- qrenco.de
#}

#(which exa > /dev/null) && alias lg="exa -lTa --git"
#lth() {
#	ls -t $@ | head
#}

#Man() {
#	nvim "man://man" "++Man $*"
#}

alias -g nu='2>/dev/null'
alias -g le='|less'
alias -g '...'='../..'
alias -g '....'='../../..'
alias -g BG='& exit'
alias -g C='|wc -l'
alias -g G='|grep -i'
alias -g H='|head'
alias -g H1=' --help |& less -r +G'
alias -g K='|keep'
alias -g L='|less +G'
alias -g LL='|& less -r'
alias -g M='|most'
alias -g N='&>/dev/null'
alias -g R='| tr A-z N-za-m'
alias -g SL='| sort | less'
alias -g S='| sort'
alias -g T='|tail'
alias -g V='| vim -'

#alias C for copy stdin
#alias X for clear + pwd (to clear screen while changing dir)

#alias _='sudo'$
#alias _i='sudo -i'$
#alias rcsync="rsync -avr --rsh='ssh -p2222' .bashrc .vimrc .Xdefaults .tmux.conf .muttrc .bash_profile .vim .w3m .moc luke@luke.xyz:/home/luke/config"

#alias newnet="sudo systemctl restart NetworkManager"
#alias alttime="sudo timedatectl set-timezone America/New_Yourk && i3 restart"
#serversend() { rsync -avr --rsh='ssh -p 2222' $1 luke@lusk.zzz:/home/luke/public_html ;}
# bl()  {convert $@ -resize 1440x1080\> bl_$0 ;}
#alias psref="gpg-connect-agent RELOADAGENT /bye" # Refresh gpg
#alias ccat="hightlight --out-format=ansi" # Color cat - print file with syntax highlighting.


## So that sudo doesnt override aliases (doesnt work with flags)
## alias sudo='sudo '
## alias doas='doas '
#alias sudo='sudo '  # Dirty trick to force alias expansion in sudo

#alias netcon='sudo lsof -n -P -i +c 15'
#alias clr='clear;echo "Currently logged in on $(tty), as $USER in directory $PWD."'
#alias psref="gpg-connect-agent RELOADAGENT /bye"

## Search running processes
alias p="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"
#alias ps='ps auxf'

## Count all files (recursively) in the current folder
#alias countfiles="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"

## To see if a command is aliased, a file, or a built-in command
#alias checkcommand="type -t"

## Show current network connections to the server
#alias ipview="netstat -anpl | grep :80 | awk {'print \$5'} | cut -d\":\" -f1 | sort | uniq -c | sort -n | sed -e 's/^ *//' -e 's/ *\$//'"

## Alias's to show disk space and space used in a folder
#alias diskspace="du -S | sort -n -r | less"
#alias folders='du -h --max-depth=1'
#alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
#alias tree='tree -CAhF --dirsfirst'
#alias treed='tree -CAFd'

## Show all logs in /var/log
#alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"

## alias chmod commands
#alias mx='chmod a+x'
#alias 000='chmod -R 000'
#alias 644='chmod -R 644'
#alias 666='chmod -R 666'
#alias 755='chmod -R 755'
#alias 777='chmod -R 777'
#alias chx="chmod +x"

#Parenting changes perms on root
#alias chown='chown --preserve-root' alias chmod='chmod --preserve-root' alias chgrp='chgrp --preserve-root'

#alias pscgroups='ps xawf -eo pid,user,cgroup,args'

#alias sshfs='sshfs -o idmap=user -o uid=1000 -o gid=100'

#alias ping='ping -OD'
#alias ping4='ping -4'
#alias ping6='ping -6'
#alias ping='ping -c 10'

#alias ipa='ip address show scope global up'
#alias ip4='ip -4 address show scope global up'
#alias ip6='ip -6 address show scope global up'
#alias ipr='ip -4 route show scope global'
#alias ip6r='ip -6 route show scope global'

## Freaking bash time is underpowered, and it's a no-op broken reserved word in zsh
#alias time='command time'

#alias vncviewer='vncviewer -DotWhenNoCursor -FullscreenSystemKeys'

#alias dirsize="du -hd 0"   #Измеряет размер директории, в которой находитесь
#alias contsize="du -hd 1"  #Измеряет размер всех директорий в директории, в которой находитесь

#socks="ssh -D 8008 emerald -fN"

#gc="grep -c"
#gi="grep -i"
#gw="grep -w"

#killport(){
#    kill -9 $(lsof -t -i:$1)
#}

#dsh(){
#    docker exec -ti $1 /bin/bash
#}

#dip(){
#   docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $1
#}

grib() {
  if [[ -n "$1" ]]; then
    git rebase -i HEAD~"$1"
  else
    git rebase -i --root
  fi
}

alias randpass="openssl rand -base64 20"

alias known_hosts="$EDITOR ~/.ssh/known_hosts"

# macos
alias cleanup-ds-store="find . -type f -name '*.DS_Store' -ls -delete"
alias brew-update='brew update && brew upgrade && brew cleanup'
alias sleep="pmset sleep now"

# kubectl
alias k="kubectl"
alias ka="kubectl apply -f"
alias kpa="kubectl patch -f"
alias ked="kubectl edit"
alias ksc="kubectl scale"
alias kex="kubectl exec -i -t"
alias kg="kubectl get"
alias kga="kubectl get all"
alias kgall="kubectl get all --all-namespaces"
alias kinfo="kubectl cluster-info"
alias kdesc="kubectl describe"
alias ktp="kubectl top"
alias klo="kubectl logs -f"
alias kn="kubectl get nodes"
alias kpv="kubectl get pv"
alias kpvc="kubectl get pvc"

# docker
alias di='docker images'
alias dr='docker run'
alias db='docker build' 
alias dp='docker ps'
alias dps="docker ps -a"
alias di="docker images"
alias drmi="docker rmi"
alias drm="docker rm"
alias dlast="docker ps -lq" # get last docker container id
