# tofi-rs theme: fullscreen dimmed overlay with a centered list.
# Generated by Omarchy theme system from ~/.config/omarchy/themed/tofi-full.toml.tpl
# Do not edit - this file is regenerated when you change themes.

[prompt]
text = "  "
padding = 4

[results]
count = 12
spacing = 8
mode = "vertical"

[text]
color = "{{ foreground }}"
prompt_color = "{{ accent }}"
input_color = "{{ bright_foreground }}"
match_color = "{{ light_foreground }}"
selection_color = "{{ accent }}"
selection_match_color = "{{ orange }}"

[font]
name = "JetBrainsMono Nerd Font"
size = 15
hint = true

# Sizes are logical px for 1440x900 (eDP-1 @2x): tofi-rs scales "%" by the output's
# physical size, so percentages come out doubled on HiDPI.
[window]
anchor = "center"
width = 1440
height = 900
background_color = "{{ darker_background }}eb"
border_width = 0
outline_width = 0
corner_radius = 0
padding_top = 300
padding_bottom = 0
padding_left = 500
padding_right = 500
clip_to_padding = true
scale = true

[cursor]
hide = true

[input]
cursor = true
cursor_style = "block"
cursor_color = "{{ accent }}"
cursor_corner_radius = 2
