# tofi-rs theme: dmenu-style bar across the top of the screen.
# Generated by Omarchy theme system from ~/.config/omarchy/themed/tofi-bar.toml.tpl
# Do not edit - this file is regenerated when you change themes.

[prompt]
text = " run: "
padding = 8

[results]
count = 0
spacing = 16
mode = "horizontal"

[text]
color = "{{ foreground }}"
prompt_color = "{{ accent }}"
input_color = "{{ bright_foreground }}"
match_color = "{{ dark_foreground }}"
selection_color = "{{ accent }}"
selection_match_color = "{{ orange }}"

[font]
name = "JetBrainsMono Nerd Font"
size = 12
hint = true

# Sizes are logical px for 1440x900 (eDP-1 @2x): tofi-rs scales "%" by the output's
# physical size, so percentages come out doubled on HiDPI.
[window]
anchor = "top"
width = 1440
height = 30
background_color = "{{ darker_background }}"
border_width = 0
outline_width = 0
corner_radius = 0
padding_top = 4
padding_bottom = 0
padding_left = 8
padding_right = 8
clip_to_padding = true
scale = true

[cursor]
hide = true

[input]
cursor = true
cursor_style = "underscore"
cursor_color = "{{ accent }}"
cursor_thickness = 2
