# tofi-rs theme: centered launcher.
# Generated by Omarchy theme system from ~/.config/omarchy/themed/tofi.toml.tpl
# Do not edit - this file is regenerated when you change themes.

[prompt]
text = "> "
padding = 6

[results]
count = 0
spacing = 6
mode = "vertical"

[text]
color = "{{ foreground }}"
prompt_color = "{{ accent }}"
input_color = "{{ bright_foreground }}"
match_color = "{{ light_foreground }}"
selection_color = "{{ accent }}"
selection_match_color = "{{ orange }}"

[font]
name = "JetBrainsMono Nerd Font"
size = 13
hint = true

# Sizes are logical px for 1440x900 (eDP-1 @2x): tofi-rs scales "%" by the output's
# physical size, so percentages come out doubled on HiDPI.
[window]
anchor = "center"
width = 640
height = 460
background_color = "{{ background }}f2"
border_width = 2
border_color = "{{ accent }}"
outline_width = 1
outline_color = "{{ darker_background }}"
corner_radius = 12
padding_top = 16
padding_bottom = 16
padding_left = 20
padding_right = 20
clip_to_padding = true
scale = true

[cursor]
hide = true

[input]
cursor = true
cursor_style = "bar"
cursor_color = "{{ accent }}"
cursor_thickness = 2
