misc {
    enable_swallow           = true
    swallow_regex            = ^(footclient)$
}

# Dialogs
windowrule=match:title ^(Open File)(.*)$, float on
windowrule=match:title ^(Select a File)(.*)$, float on
windowrule=match:title ^(Choose wallpaper)(.*)$, float on
windowrule=match:title ^(Open Folder)(.*)$, float on
windowrule=match:title ^(Save As)(.*)$, float on
windowrule=match:title ^(Library)(.*)$, float on
windowrule=match:title ^(File Upload)(.*)$, float on
windowrule=match:title ^(Rename)(.*)$, float on

workspace=special:whatsapp,persistent:true,gapsout:300
workspace=special:firefox,persistent:true,gapsout:40, gapsin:40
