# tofi-rs config for piping: printf 'a\nb\n' | tofi -c ~/.config/tofi/dmenu.toml

[base]
mode = "dmenu"
theme = "omarchy.toml"

[matching]
algorithm = "normal"
require = true

[history]
history = false
